

USE warehouseSchema;

DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESCRIPTION` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PRICE` decimal(50,30) DEFAULT NULL,
  `VERSION` int DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;


