


USE warehouseSchema;

DROP TABLE IF EXISTS `ORDER`;


CREATE TABLE IF NOT EXISTS `ORDER` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `BUYER_EMAIL` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATION_DATE` datetime DEFAULT NULL,
  `VERSION` int DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

