

USE warehouseSchema;

DROP TABLE IF EXISTS `ORDER_LINE`;


CREATE TABLE IF NOT EXISTS `ORDER_LINE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` bigint DEFAULT NULL,
  `PRODUCT_ID` bigint DEFAULT NULL,
  `QUANTITY` int DEFAULT '1',
  `PRODUCT_PRICE` decimal(50,30) DEFAULT NULL COMMENT 'Price of the product when the order is processed',
  `VERSION` int DEFAULT 0,
  PRIMARY KEY (`ID`),
  KEY `FK_ORDER_LINE_ORDER_ID` (`ORDER_ID`),
  KEY `FK_ORDER_LINE_PRODUCT_ID` (`PRODUCT_ID`),
  CONSTRAINT `ORDER_LINE_ibfk_1` FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER` (`ID`),
  CONSTRAINT `ORDER_LINE_ibfk_2` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;




